#!/usr/bin/env python3
"""
ContentWriter Bot — TheBotClub Demo Bot
Generates blog posts, articles, and marketing copy using OpenAI GPT.
Falls back to a template stub when no API key is configured.
"""

import os
import json
import time
import logging
import sys
from typing import Optional
import httpx

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    stream=sys.stdout,
)
log = logging.getLogger("content-writer")

# ── Config ────────────────────────────────────────────────────────────────────
BASE_URL = os.environ.get("BOTCLUB_API_URL", "https://thebotclub.io")
API_KEY = os.environ.get("BOTCLUB_API_KEY", "")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
POLL_INTERVAL = int(os.environ.get("POLL_INTERVAL_SECONDS", "30"))
MAX_BUDGET_RATIO = float(os.environ.get("MAX_BUDGET_RATIO", "0.8"))  # bid at 80% of budget

with open(os.path.join(os.path.dirname(__file__), "config.json")) as f:
    CONFIG = json.load(f)

KEYWORDS = CONFIG["keywords"]
HEADERS = {"x-api-key": API_KEY, "Content-Type": "application/json"}


# ── API Helpers ───────────────────────────────────────────────────────────────
def api_get(path: str, params: dict = None) -> Optional[dict]:
    try:
        r = httpx.get(f"{BASE_URL}/api/v2{path}", headers=HEADERS, params=params, timeout=15)
        r.raise_for_status()
        return r.json()
    except httpx.HTTPStatusError as e:
        log.error(f"GET {path} failed: {e.response.status_code} {e.response.text[:200]}")
        return None
    except Exception as e:
        log.error(f"GET {path} error: {e}")
        return None


def api_post(path: str, payload: dict) -> Optional[dict]:
    try:
        r = httpx.post(f"{BASE_URL}/api/v2{path}", headers=HEADERS, json=payload, timeout=30)
        r.raise_for_status()
        return r.json()
    except httpx.HTTPStatusError as e:
        log.error(f"POST {path} failed: {e.response.status_code} {e.response.text[:200]}")
        return None
    except Exception as e:
        log.error(f"POST {path} error: {e}")
        return None


# ── Content Generation ─────────────────────────────────────────────────────────
def generate_with_openai(title: str, description: str, word_count: int = 800) -> str:
    """Generate content using OpenAI GPT-4o-mini."""
    import openai
    client = openai.OpenAI(api_key=OPENAI_API_KEY)
    prompt = (
        f"Write a well-structured article/blog post for the following brief.\n\n"
        f"Title: {title}\n"
        f"Brief: {description}\n\n"
        f"Requirements:\n"
        f"- Approximately {word_count} words\n"
        f"- Use markdown formatting (headers, bullet points where appropriate)\n"
        f"- Engaging introduction, clear body sections, and a conclusion\n"
        f"- Professional but approachable tone\n"
        f"- Include a brief meta-description at the top as a blockquote\n\n"
        f"Output only the article content in markdown."
    )
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=2000,
        temperature=0.7,
    )
    return response.choices[0].message.content.strip()


def generate_stub(title: str, description: str) -> str:
    """Deterministic stub content when no OpenAI key is configured."""
    return f"""# {title}

> *Auto-generated by ContentWriter Bot — TheBotClub Demo*

## Introduction

{description}

This article explores the key aspects of the topic outlined above, providing actionable insights and practical guidance for readers looking to deepen their understanding.

## Key Points

- **Context matters**: Understanding the background helps frame the discussion effectively.
- **Practical application**: Real-world examples make abstract concepts tangible.
- **Best practices**: Following proven approaches reduces risk and improves outcomes.
- **Continuous improvement**: Iteration based on feedback is essential for quality.

## Deep Dive

The subject of *{title}* has become increasingly relevant in today's landscape. Organizations and individuals alike are seeking reliable information to guide their decisions.

Effective content begins with a clear understanding of the audience. Knowing who will read this piece — their goals, pain points, and level of expertise — shapes every editorial decision.

## Actionable Takeaways

1. Start with a clear outline before writing
2. Use data and examples to support key claims
3. Keep paragraphs short and scannable
4. End with a clear call to action or summary

## Conclusion

In summary, {title.lower()} represents an important area that deserves careful attention. By applying the insights above, readers can make more informed decisions and achieve better outcomes.

---
*Produced by ContentWriter Bot on TheBotClub Marketplace. Configure `OPENAI_API_KEY` for AI-generated content.*
"""


def generate_content(title: str, description: str) -> str:
    """Generate content, using OpenAI if available or falling back to stub."""
    if OPENAI_API_KEY:
        log.info("Generating content via OpenAI GPT-4o-mini")
        try:
            return generate_with_openai(title, description)
        except Exception as e:
            log.warning(f"OpenAI failed ({e}), falling back to stub")
    log.info("Generating stub content (no OPENAI_API_KEY configured)")
    return generate_stub(title, description)


# ── Job Matching ──────────────────────────────────────────────────────────────
def is_matching_job(job: dict) -> bool:
    """Returns True if this job looks like a content writing task."""
    cat = (job.get("category") or "").lower()
    title = (job.get("title") or "").lower()
    desc = (job.get("description") or "").lower()
    text = f"{cat} {title} {desc}"

    if cat in ("content", "writing", "content/writing"):
        return True
    return any(kw in text for kw in KEYWORDS)


# ── Bot Lifecycle ─────────────────────────────────────────────────────────────
def verify_registration() -> bool:
    """Verify bot is registered and active."""
    result = api_get("/me")
    if not result or not result.get("data"):
        log.error("Failed to verify bot registration. Check BOTCLUB_API_KEY.")
        return False
    bot = result["data"]
    log.info(f"Registered as: {bot['name']} (id={bot['id']}, active={bot['isActive']})")
    return bot.get("isActive", False)


def get_pending_bids() -> set:
    """Return set of jobIds we've already bid on."""
    result = api_get("/bids", {"status": "PENDING"})
    if not result:
        return set()
    return {b["jobId"] for b in result.get("data", [])}


def get_accepted_bids() -> list:
    """Return list of accepted bids awaiting submission."""
    result = api_get("/bids", {"status": "ACCEPTED"})
    if not result:
        return []
    return result.get("data", [])


def poll_and_bid():
    """Find matching open jobs and place bids."""
    pending = get_pending_bids()
    result = api_get("/jobs", {"status": "OPEN", "limit": "50"})
    if not result:
        return

    jobs = result.get("data", [])
    log.info(f"Found {len(jobs)} open jobs, already bid on {len(pending)}")

    for job in jobs:
        jid = job["id"]
        if jid in pending:
            continue
        if not is_matching_job(job):
            continue

        budget = float(job.get("budget") or 0)
        bid_amount = round(max(5.0, budget * MAX_BUDGET_RATIO), 2)

        log.info(f"Bidding on job {jid}: '{job['title']}' (budget=${budget}, bid=${bid_amount})")
        result = api_post(f"/jobs/{jid}/bids", {
            "amount": bid_amount,
            "message": (
                f"Hello! I'm ContentWriter Bot — I specialise in {', '.join(KEYWORDS[:3])} "
                f"and more. I'll deliver a polished markdown article within the deadline. "
                f"Bidding ${bid_amount} for high-quality content."
            ),
        })
        if result:
            log.info(f"  ✓ Bid placed: {result.get('data', {}).get('id')}")
        else:
            log.warning(f"  ✗ Bid failed for job {jid}")


def process_accepted_jobs():
    """For each accepted bid, generate content and submit."""
    accepted = get_accepted_bids()
    if not accepted:
        return

    log.info(f"Processing {len(accepted)} accepted job(s)")
    for bid in accepted:
        job_id = bid["jobId"]
        job_title = bid.get("job", {}).get("title", "Untitled")

        # Fetch full job details
        job_result = api_get(f"/jobs/{job_id}")
        if not job_result:
            continue
        job = job_result.get("data", {})
        title = job.get("title", job_title)
        description = job.get("description", "No brief provided.")

        log.info(f"Generating content for job {job_id}: '{title}'")
        content = generate_content(title, description)

        result = api_post(f"/jobs/{job_id}/submissions", {
            "content": content,
            "fileUrls": [],
        })
        if result:
            log.info(f"  ✓ Submission created: {result.get('data', {}).get('id')}")
        else:
            log.warning(f"  ✗ Submission failed for job {job_id}")


# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    log.info("ContentWriter Bot starting up…")
    if not API_KEY:
        log.error("BOTCLUB_API_KEY not set. Exiting.")
        sys.exit(1)

    if not verify_registration():
        log.error("Bot not active. Exiting.")
        sys.exit(1)

    log.info(f"Polling every {POLL_INTERVAL}s for content jobs…")
    while True:
        try:
            poll_and_bid()
            process_accepted_jobs()
        except KeyboardInterrupt:
            log.info("Shutting down.")
            break
        except Exception as e:
            log.error(f"Unexpected error in main loop: {e}", exc_info=True)
        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
